### ISSUE TITLE
tt

### ISSUE THREAD

**Issue by ppamppamman** [ppamppamman/ppamppamman.github.io#20]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzRkNGYyMjktMTIwNy00YmVkLTk0YmItZTY4ZWY0NWE4Yjdm%40thread.v2/0?context=%7b%22Tid%22%3a%22e5f2d2b8-0d14-454b-b0a7-2cb6b56ae80e%22%2c%22Oid%22%3a%22d3e71b2a-3937-4c67-a67d-72325be48dbb%22%7d)

**Comment by Jerome-Yoo** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzRkNGYyMjktMTIwNy00YmVkLTk0YmItZTY4ZWY0NWE4Yjdm%40thread.v2/0?context=%7b%22Tid%22%3a%22e5f2d2b8-0d14-454b-b0a7-2cb6b56ae80e%22%2c%22Oid%22%3a%22d3e71b2a-3937-4c67-a67d-72325be48dbb%22%7d

**Comment by Jerome-Yoo** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzRkNGYyMjktMTIwNy00YmVkLTk0YmItZTY4ZWY0NWE4Yjdm%40thread.v2/0?context=%7b%22Tid%22%3a%22e5f2d2b8-0d14-454b-b0a7-2cb6b56ae80e%22%2c%22Oid%22%3a%22d3e71b2a-3937-4c67-a67d-72325be48dbb%22%7d
